### ISSUE TITLE
IE11 Timeline bug

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/lab-site#108]
Object doesn't support property or method 'from'
index-timeline.js (2,268)

 const embeds = Array.from(document.querySelectorAll('.embed'));

**index-timeline.js is not transpiled!!!**

**Comment by fabianmoronzirfas** [comment]
Is this done? Or should I take a look at it?

**Comment by sebastian-meier** [comment]
it's done. i implemented a polyfill for that...
