### ISSUE TITLE
mobile - first menu item overlaps with logo-title

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/lab-site#117]
on small screens. just a little more offset at the top.

**Comment by fabianmoronzirfas** [comment]
![A83B981A-2901-414B-8981-3B8AB4285808](https://user-images.githubusercontent.com/315106/56613965-1fc89c80-6618-11e9-9ffe-1d998a49793e.png)
![8AA3C603-6A9F-4CE5-B677-D06FF5ACEBC9](https://user-images.githubusercontent.com/315106/56613968-1fc89c80-6618-11e9-9507-45a084f21671.png)
Firefox ans Chrome on iOS latest
