### ISSUE TITLE
social media cards still not working

### ISSUE THREAD

**Issue by bnjmnsbl** [technologiestiftung/lab-site#152]
not on twitter, not on facebook :(

**Comment by fabianmoronzirfas** [comment]
Hm. The image is availalbe https://lab.technologiestiftung-berlin.de/assets/images/social_media.jpg - So it might be a problem with the size?

**Comment by fabianmoronzirfas** [comment]
```html
<meta name="twitter:image" content="/assets/images/social_media.jpg">
```

**Comment by fabianmoronzirfas** [comment]
Does this need a URL with a hostname?

**Comment by sebastian-meier** [comment]
yeah, we might need absolute urls. they were absolute in the old site...
