### ISSUE TITLE
Is there a root index.html 

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/lab-site#16]
related to #4

**Comment by fabianmoronzirfas** [comment]
when running `npm run dev` there is nothing at `localhost:3000`

**Comment by fabianmoronzirfas** [comment]
How come that on https://pedantic-mirzakhani-1841cc.netlify.com there is content on the root? @sebastian-meier

**Comment by sebastian-meier** [comment]
the build script, similar to github itself uses the dist folder as its output root, not the project root

**Comment by fabianmoronzirfas** [comment]
Okay. But then we still have the problem on GitHub Pages that our root is empty and has no index.html.

```plain
.
├── README.md
├── dist
│   ├── assets
│   ├── de
│   ├── en
│   ├── js
│   └── styles
├── getProjectPrompts.js
├── gulpfile.js
├── package-lock.json
├── package.json
├── projects
│   ├── example-project
│   └── first-project
└── src
    ├── assets
    ├── data
    ├── js
    ├── styles
    └── templates
```

**Comment by fabianmoronzirfas** [comment]
My version was old. Sorry for the fuzz @fdnklg
