### ISSUE TITLE
Description in XML feed is still generic

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/lab-site#203]
Currently the [feed](https://github.com/technologiestiftung/lab-site/blob/master/source/feed.xml#L7) uses the content from [_config.yml](https://github.com/technologiestiftung/lab-site/blob/master/_config.yml#L23).  

- [ ] Should we write a relevant one @bnjmnsbl 
- [ ] Use the one from the [meta.json](https://github.com/technologiestiftung/lab-site/blob/master/source/_data/meta.json#L16)

**Comment by bnjmnsbl** [comment]
done
