### ISSUE TITLE
translation: translate funding in footer

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/lab-site#38]

**Comment by fabianmoronzirfas** [comment]
@tori-d could you translate this?  

> Gefördert von der Senatsverwaltung für Wirtschaft, Energie und Betriebe und der Investitionsbank Berlin aus den Mitteln des Landes Berlin.

**Comment by tori-d** [comment]
Financial support provided by the Senate Department for Economics, Energy and Public Enterprises and the Investitionsbank Berlin via funds from the State of Berlin.

**Comment by fabianmoronzirfas** [comment]
thanks. Fixed with 346c931accbeabd6c917f787c7201edcaddc9ace
