### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/lab-site#4]
Due to new folder structures the old files need to be redirected to the new files.
This needs to be done through 301 (SEO!). Hosting the site on github/netlify there is not htaccess, need to find another way to redirect pages...

**Comment by fabianmoronzirfas** [comment]
Maybe we need a setup like this:  

Push to repo -> Travis Build (or GitHub Actions) -> Push back to other branch of Repo Which holds the GitHub Pages -> Jekyll build creates redirects

**Comment by fabianmoronzirfas** [comment]
See #2 for a simple travis setup

**Comment by fabianmoronzirfas** [comment]
haha. I tried to create an elaborate travis-ci script that does the deployment to github pages. It looks travis has that build in.

https://docs.travis-ci.com/user/deployment/pages/

**Comment by fabianmoronzirfas** [comment]
And some more fun stuff we can do with travis and jekyll. The workflow below allows to also have custom Jekyll plugins.

- https://medium.com/@mcred/supercharge-github-pages-with-jekyll-and-travis-ci-699bc0bde075
- https://jekyllrb.com/docs/continuous-integration/travis-ci/
