### ISSUE TITLE
social media image

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/lab-site#45]

**Comment by sebastian-meier** [comment]
Social Media Images currently direct to "http://localhost:4000/icons/social_media.jpg"

In order to get going, i am recommending that we use the heroImage as a social media fallback.
In addition i would add a fourth image socialMedia to the front matter.

**Comment by fabianmoronzirfas** [comment]
@sebastian-meier but doesn't that image has to be a specific size? Or can we just use the heroImage?

**Comment by fabianmoronzirfas** [comment]
Done.

**Comment by fabianmoronzirfas** [comment]
Key `socialMediaImage` is part of the default frontmatter created by project-generator. https://github.com/technologiestiftung/lab-site/commit/660cf1d33ac32b9795ab01dda488744d3aafbbc1#diff-96e7d871ded13fb11a5a242ff73e650bR37
