### ISSUE TITLE
Images very large in macro-image-section-markdown.html on full screen

### ISSUE THREAD

**Issue by AlexandraKapp** [technologiestiftung/lab-site#47]
images get too large on desktop full screen. Maybe define max-width for images?
![bildschirmfoto 2019-02-18 um 11 52 37](https://user-images.githubusercontent.com/18367515/52946226-d5a31080-3373-11e9-9ae3-a6a54e0ee849.png)

**Comment by fdnklg** [comment]
macro for smaller images added:
-> macro-image-section-markdown-small.html
