### ISSUE TITLE
review: Do we need inline SVG images?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/lab-site#50]
@fdnklg It makes the source pretty unreadable and creates duplicate code.

**Comment by fdnklg** [comment]
SVGs need to be placed inline to animate their shapes. So I'd like to keep these inline.

**Comment by fabianmoronzirfas** [comment]
Okay. Still would be good to put them into an include rather then having them in the layout for better readability

**Comment by fabianmoronzirfas** [comment]
See the above commit b0ccb64

**Comment by fabianmoronzirfas** [comment]
Is it 2 times the same svg code that is inline?

**Comment by sebastian-meier** [comment]
Static SVGs should be included as external images (for example funding.html), animated SVGs should be included through jekyll-includes for readability purposes...

**Comment by sebastian-meier** [comment]
@fdnklg can this be closed?

**Comment by fdnklg** [comment]
Inline SVG's are now encapsuled in external SVG files.
