### ISSUE TITLE
check meta on all articles

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/lab-site#60]
some articles that were created in earlier stages of the project are missing certain meta values...

**Comment by sebastian-meier** [comment]
Social Media Image on non-project sites is non-existent
@fdnklg > Add Default Social Media Image
@fabianmoronzirfas > Map Default Social Media Image in Correct Folger

**Comment by sebastian-meier** [comment]
@fabianmoronzirfas Social Media Meta Data on project pages should be based upon individual projects, sofar social media meta is always the same. On Non-Home and Non-Project Pages, at least the title should change, description etc. can stay the same.

**Comment by sebastian-meier** [comment]
@fabianmoronzirfas > so i manually updated all projects and their social media images, and added new images where non existed... i now sadly hand over the header-meta if/else mess to you :)

**Comment by fabianmoronzirfas** [comment]
should be done.
If a page has a description it will overrule the default description. 
description in `_config.yml` is DEPRECATED

**Comment by sebastian-meier** [comment]
title as well?

**Comment by fabianmoronzirfas** [comment]
Yes.

```html
{%- if page.layout == 'landing' -%}
    {%- assign title = site.data.meta.title.en -%}
  {%- else -%}
    {%- assign title = site.data.meta.title.en | append: " | " | append: page.title  -%}
{%- endif -%}
```
If there is no page title it will look like this:

```html
Ideation & Prototyping Lab | 
```

**Comment by fabianmoronzirfas** [comment]
could be enhanced

**Comment by fabianmoronzirfas** [comment]
Done.
