### ISSUE TITLE
Thumbnail templates / Template Styling

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/lab-site#7]
The color of thumbnails should be applied through CSS. 

A few example thumbnails with matching grayscale and filters should be made available (Ideally in Photoshop and GIMP). Or an explanation which filters to apply to generate those gray thumbnail images.

**Comment by sebastian-meier** [comment]
@sebastian-meier adds type-specific css-classes to each thumbnail

**Comment by fabianmoronzirfas** [comment]
Gimp can open PSD files but there are some limitations. Here is a page with a rundown what is not supported https://wiki.gimp.org/wiki/PSD_support

**Comment by fabianmoronzirfas** [comment]
added Gimp files with b8e8193ba1459432139a291f4bbe6c8b9ac0b573 They still need a lot of love. All the adjustment layers are gone.

**Comment by fabianmoronzirfas** [comment]
Looks like there is no equivalent to non destructive editing with adjustment layers in Gimp. There is this post that tries to mimic this feature https://www.tablix.org/~avian/blog/archives/2018/03/faking_adjustment_layers_with_gimp_layer_modes/ The feature is on the Roadmap for Gimp 3.2 which is in the far future https://wiki.gimp.org/index.php/Roadmap
