### ISSUE TITLE
Transpile VIS-Code

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/lab-site#76]
Funding, etc.

**Comment by sebastian-meier** [comment]
polyfills for fetch.js & promise (e.g. bluebird)

**Comment by fabianmoronzirfas** [comment]
re #77

**Comment by fabianmoronzirfas** [comment]
Polyfills are there. IE-Tests are working. Can we close this?

**Comment by sebastian-meier** [comment]
nope, this ticket is for me, to go through the custom code snippets on the sites and make sure they are all good, will do this today...
