### ISSUE TITLE
Add Mission Statement to About Page

### ISSUE THREAD

**Issue by bnjmnsbl** [technologiestiftung/lab-site#78]
On the about page, there should be a separate section with a mission statement ("about the lab", blindtext fine for now) before the team section.

**Comment by fabianmoronzirfas** [comment]
Ah. Okay. I thought it was something that is per person…

So you want a general statement that appears on each about page right?

**Comment by fabianmoronzirfas** [comment]
Added switch statement for language and minimal markup. It is still un-styled though. @fdnklg can you take over?

@bnjmnsbl The text can be changed in `source/_data/meta.json` in 

```json
"missionStatement":{
    "title":{
      "de": "Leitbild",
      "en": "Mission Statement"
    },
    "text":{
      "de": "Dies ist ein Typoblindtext. An ihm kann man sehen, ob alle Buchstaben da sind und wie sie aussehen. Manchmal benutzt man Worte wie Hamburgefonts, Rafgenduks oder Handgloves, um Schriften zu testen. Manchmal Sätze, die alle Buchstaben des Alphabets enthalten - man nennt diese Sätze »Pangrams«.",
      "en": "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections."
    }
  },
```

**Comment by fabianmoronzirfas** [comment]
of course you need to pull. :-)

**Comment by fabianmoronzirfas** [comment]
@fdnklg This still needs stying and markup
@bnjmnsbl This still needs some text
