### ISSUE TITLE
Fallback Hero Image

### ISSUE THREAD

**Issue by bnjmnsbl** [technologiestiftung/lab-site#79]
In case no hero image is specified on a project page, there should be a fallback to a standard background image (that we can use for news, announcements etc.) – feel free to design something simple (could be a variation of our logo, a generic pic or even just a plain color/transition background)

**Comment by fabianmoronzirfas** [comment]
014510a9bb446366864e5fa7bcf1e0d00923c2e2 Adds a fallback hero image. Only works if the key for heroImage is not present. If the path is wrong it will generate a resource error (as it does normally). The file added in that commit is in `source/assets/images/placeholder-hero.png` and need some styling.

**Comment by fdnklg** [comment]
Basic styling added. In general we'd like to use individual images for each article we publish. It's also possible to use the same imagery for thumbnail and hero image.
