### ISSUE TITLE
bundle is too large

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/lab-site#83]
I could not figure this out, but the bundle.index.js is pretty large. Even if i combine all non minified scripts that should go into the bundle i don't reach the 1.3 MB ??? And of course the bundle should be minified.

**Comment by fabianmoronzirfas** [comment]
I guess the "to large" comes from the polyfills we are adding for supporting IE.
The minify can be done by running `parcel build` instead of `parcel watch` I figure something out.

**Comment by fabianmoronzirfas** [comment]
Added the script `npm run build:js` to run a production build. Reduces the size to 621.7KB. I really want to automate this for the future. Currently the option is travis. IN the future we could use github.actions to do this. Both will need a additional commit and push to the repo.  

```bash
└> npm run build:js

> lab-site@1.0.0 build:js /Users/icke/Documents/tsberlin/lab-site
> parcel build source/assets/js/index.js --no-cache --out-dir source/assets/js/ --out-file index.bundle.js --public-url .

✨  Built in 12.95s.

source/assets/js/index.bundle.js.map    ⚠️  1.51 MB     207ms
source/assets/js/index.bundle.js          621.7 KB    12.35s
```

**Comment by fabianmoronzirfas** [comment]
@fdnklg The timeline.js does some import from the D3 library. I assume this is the one in `package.json v5.8.2`.

We also have D3 minified in the assets. Can we use one that is globally included?

When running the script without Timeline.js included we have the following result

```bash
└> npm run build:js

> lab-site@1.0.0 build:js /Users/icke/Documents/tsberlin/lab-site
> parcel build source/assets/js/index.js --no-cache --out-dir source/assets/js/ --out-file index.bundle.js --public-url .

✨  Built in 5.74s.

source/assets/js/index.bundle.js.map    419.03 KB     56ms
source/assets/js/index.bundle.js        169.27 KB    5.33s
```  

Due to the fact that the timeline is only on the landing page we could reduce the load on our visitors.

**Comment by fabianmoronzirfas** [comment]
see PR #84 with my suggestion

**Comment by fabianmoronzirfas** [comment]
@fdnklg Will you consider this? or is this for the backlog?
