### ISSUE TITLE
Some content is not translated in /ource/projects/funding/en/index.html

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/lab-site#86]
- https://github.com/technologiestiftung/lab-site/blob/migrate/new-labsite/source/projects/funding/en/index.html#L108
- https://github.com/technologiestiftung/lab-site/blob/migrate/new-labsite/source/projects/funding/en/index.html#L42

**Comment by sebastian-meier** [comment]
funding is by @dinklage

**Comment by sebastian-meier** [comment]
@fdnklg schaust du nochmal...
