### ISSUE TITLE
Comments in the HTML

### ISSUE THREAD

**Issue by sebastian-meier** [technologiestiftung/lab-site#90]
There are some dev-comments in the HTML code. I think those should be removed,  maybe convert to jekyll notes.

**Comment by fabianmoronzirfas** [comment]
Should be done with 9ed6a642d84916421c23c274dbafdc8340441c58 and d6fb446d796890692415747f706cc147dd8f1d2e -> Closing `this`.

I also added a vscode snippet to enclose the selection in a Jekyll comment

```html
{%- comment -%} Jekyll should ignore this {%- endcomment -%}

```
